server:
  port: 8700

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: produtos
          uri: lb://PRODUTOS
          predicates:
            - Path=/produtos/**

        - id: pedidos
          uri: lb://PEDIDOS
          predicates:
            - Path=/pedidos/**

